### ISSUE TITLE
Old source

### ISSUE THREAD

**Issue by ariebrainware** [gunturkh/learn-orm#2]
You need to change this debugging process
https://github.com/gunturkh/learn-orm/blob/2d001d911fa2ddcd2249fb674c2db690ffc74be6/index.js#L20

**Comment by gunturkh** [comment]
Ok rie i'l fix this ASAP

**Comment by ariebrainware** [comment]
And dont user ```render``` just use ```res.send({message:'yourerrormessage'})```
https://github.com/gunturkh/learn-orm/blob/43ffdac50712f0642d15f103e03a4de7f71d4d12/app.js#L39
